### ISSUE TITLE
Update check always says the current version is old

### ISSUE THREAD

**Issue by mreiger** [metal-stack/updater#1]
Update check compares the dates of two different events:
- For github, the publishing time of the release
- For the local file, the build date from the local version info

Since the publishing time of the release is always a bit later than the build date, update check will always see the local binary as old and recommend updating.

Sample output from [cloudctl](https://github.com/fi-ts/cloudctl):
```bash
michael@metalmachine:~/Software/metal$ cloudctl update check
checksum:b72bc17c6f692c78de69a646530d2cbd
latest version:v0.7.13 from:2020-07-21T12:35:54Z
local  version:v0.7.13 from:2020-07-21T12:34:08Z
cloudctl is 1m 46s old, please run 'cloudctl update do'
cloudctl location:/usr/local/bin/cloudctl
```
I can see two ways to fix this:
1. Base the comparison of releases on the tag, not the build/release time
2. Introduce a grace period of e.g. 5 minutes so that the small time difference will not matter

Personally I would prefer 1. :-)

**Comment by majst01** [comment]
semver comparison is the way to go.
